apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerized
  labels:
    app: dockerized
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dockerized
  template:
    metadata:
      labels:
        app: dockerized
    spec:
      containers:
        - name: dockerized
          image: dockerized:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: dockerized-service
spec:
  type: NodePort
  selector:
    app: dockerized
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
